### ISSUE TITLE
addEngine / pixelsmith support

### ISSUE THREAD

**Issue by mvenghaus** [bevacqua/spritesmith-cli#2]
Hello,

i see currently no possiblity to add a custom engine like pixelsmith. I've to write this hard in your files. Can you add support .. something like that:

function run (data) {

  if (data.engineOpts && data.engineOpts.load) {
    spritesmith.addEngine(data.engine, require(data.engine));
  }

**Comment by bevacqua** [comment]
Feel free to send pr
